In [1]:
import pandas as pd
import numpy as np
import os
import sklearn.metrics as sklm
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv("drugConsumption_5Response.csv")
data

id      Age   Gender  Education  Country  Ethnicity  Neuroticism  \
0        1.0  0.49788  0.48246   -0.05921  0.96082    0.12600      0.31287   
1        2.0 -0.07854 -0.48246    1.98437  0.96082   -0.31685     -0.67825   
2        3.0  0.49788 -0.48246   -0.05921  0.96082   -0.31685     -0.46725   
3        4.0 -0.95197  0.48246    1.16365  0.96082   -0.31685     -0.14882   
4        5.0  0.49788  0.48246    1.98437  0.96082   -0.31685      0.73545   
...      ...      ...      ...        ...      ...        ...          ...   
1880  1884.0 -0.95197  0.48246   -0.61113 -0.57009   -0.31685     -1.19430   
1881  1885.0 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685     -0.24649   
1882  1886.0 -0.07854  0.48246    0.45468 -0.57009   -0.31685      1.13281   
1883  1887.0 -0.95197  0.48246   -0.61113 -0.57009   -0.31685      0.91093   
1884  1888.0 -0.95197 -0.48246   -0.61113  0.21128   -0.31685     -0.46725   

      Extraversion  Openness  Agreeableness  Conscientiousness  Impulsive  \
0         -0.57545  -0.58331       -0.91699           -0.00665   -0.21712   
1          1.93886   1.43533        0.76096           -0.14277   -0.71126   
2          0.80523  -0.84732       -1.62090           -1.01450   -1.37983   
3         -0.80615  -0.01928        0.59042            0.58489   -1.37983   
4         -1.63340  -0.45174       -0.30172            1.30612   -0.21712   
...            ...       ...            ...                ...        ...   
1880       1.74091   1.88511        0.76096           -1.13788    0.88113   
1881       1.74091   0.58331        0.76096           -1.51840    0.88113   
1882      -1.37639  -1.27553       -1.77200           -1.38502    0.52975   
1883      -1.92173   0.29338       -1.62090           -2.57309    1.29221   
1884       2.12700   1.65653        1.11406            0.41594    0.88113   

      Sensation Seeking  Benzos  Caffeine  Cocaine  LSD  Heroin  
0              -1.18084     0.0       1.0      0.0  0.0     0.0  
1              -0.21575     0.0       1.0      1.0  0.0     0.0  
2               0.40148     0.0       1.0      0.0  0.0     0.0  
3              -1.18084     1.0       1.0      0.0  0.0     0.0  
4              -0.21575     0.0       1.0      0.0  0.0     0.0  
...                 ...     ...       ...      ...  ...     ...  
1880            1.92173     0.0       1.0      0.0  1.0     0.0  
1881            0.76540     0.0       1.0      0.0  1.0     0.0  
1882           -0.52593     1.0       1.0      1.0  0.0     0.0  
1883            1.22470     0.0       1.0      0.0  1.0     0.0  
1884            1.22470     1.0       1.0      1.0  1.0     0.0  

[1885 rows x 18 columns]

In [21]:
from sklearn.model_selection import train_test_split
drugs = ["Benzos", "Caffeine","Cocaine","LSD","Heroin"]
X = data[['Age','Gender','Education', 'Country', 'Ethnicity', 'Neuroticism', 'Extraversion', 'Openness', 'Agreeableness', 'Conscientiousness', 'Impulsive', 'Sensation Seeking']]
y_testall = np.zeros((472,5))
yhat_all = np.zeros((472,5))
yhat_prob = np.zeros((472,5))


In [22]:
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, data.Benzos, test_size = 0.25, random_state=42)
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
pred = model.predict(X_test)
sb = model.score(X_test, y_test)
#sklm.roc_auc_score(y_test, model.predict_proba(X_test)[:,1])
sklm.confusion_matrix(y_test,pred)

array([[288,  42],
       [ 86,  56]])

In [23]:
yhat_all[:,0] = pred
y_testall[:,0] = y_test
yhat_prob[:,0] = model.predict_proba(X_test)[:,1]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, data.Caffeine, test_size = 0.25, random_state=42)
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
pred = model.predict(X_test)
sC = model.score(X_test, y_test)
sklm.confusion_matrix(y_test,pred)

array([[  0,  16],
       [  0, 456]])

In [25]:
yhat_all[:,1] = pred
y_testall[:,1] = y_test
yhat_prob[:,1] = model.predict_proba(X_test)[:,1]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, data.Cocaine, test_size = 0.25, random_state=42)
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
pred = model.predict(X_test)
sCoc = model.score(X_test, y_test)
sklm.confusion_matrix(y_test,pred)

array([[350,  16],
       [ 87,  19]])

In [27]:
yhat_all[:,2] = pred
y_testall[:,2] = y_test
yhat_prob[:,2] = model.predict_proba(X_test)[:,1]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, data.LSD, test_size = 0.25,random_state=42)
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
pred = model.predict(X_test)
sL = model.score(X_test, y_test)
sklm.confusion_matrix(y_test,pred)

array([[331,  42],
       [ 50,  49]])

In [29]:
yhat_all[:,3] = pred
y_testall[:,3] = y_test
yhat_prob[:,3] = model.predict_proba(X_test)[:,1]

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, data.Heroin, test_size = 0.25,random_state=42)
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
pred = model.predict(X_test)
sH = model.score(X_test, y_test)
sklm.confusion_matrix(y_test,pred)

array([[438,   0],
       [ 34,   0]])

In [31]:
yhat_all[:,4] = pred
y_testall[:,4] = y_test
yhat_prob[:,4] = model.predict_proba(X_test)[:,1]

In [34]:
hamming = sklm.hamming_loss(y_testall,yhat_all)
subsetacc = sklm.accuracy_score(y_testall,yhat_all)
aucA = sklm.roc_auc_score(y_testall,yhat_prob,average=None)
auc = sklm.roc_auc_score(y_testall,yhat_prob,average='weighted')

In [35]:
print(hamming)
print(subsetacc)
print(auc)
print(aucA)

0.15805084745762712
0.5127118644067796
0.7514228488259718
[0.76564234 0.70847039 0.80546964 0.83784223 0.84797207]


In [41]:
mcm = sklm.multilabel_confusion_matrix(y_testall,yhat_all)
print(mcm)

[[[288  42]
  [ 86  56]]

 [[  0  16]
  [  0 456]]

 [[350  16]
  [ 87  19]]

 [[331  42]
  [ 50  49]]

 [[438   0]
  [ 34   0]]]


In [42]:
tn = mcm[:, 0, 0]
tp = mcm[:, 1, 1]
fn = mcm[:, 1, 0]
fp = mcm[:, 0, 1]

In [43]:
recall = tp / (tp + fn)
print(recall)

[0.3943662  1.         0.17924528 0.49494949 0.        ]


In [44]:
specificity = tn / (tn + fp)
print(specificity)

[0.87272727 0.         0.95628415 0.88739946 1.        ]
